<b>Data Representation | Vectorization</b> <br>

Have fixed size:
- Audio --> frequency
- image --> pixel
- video --> sequence of images

So, this are easy to do tokenization

<br>

But to text data, there is no fixed dimension. <br>

There are two techniques to handle it:
1. one hot encoding
```
    - should not follow this
    - Drawbaceks:
        - sparsity
        - no fixed size
        - OOV
        - not capturing sementic meaning
```

2. bag of words
```
    - not capture sementic meaning
```

In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({
       "text":[
              "people watch dswithbappy",
              "dswithbappy watch dswithbappy",
              "people write comment",
              "dswithbappy write comment"],
       "output":[1,1,0,0]
})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

## Bag of words

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

# Unigrams
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])

In [5]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)

In [8]:
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]], dtype=int64)

In [11]:
X = bow.toarray()
y = df['output']

X

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)