<b>Data Representation | Vectorization</b> <br>

Have fixed size:
- Audio --> frequency
- image --> pixel
- video --> sequence of images

So, this are easy to do tokenization

<br>

But to text data, there is no fixed dimension. <br>

There are two techniques to handle it:
1. one hot encoding
```
    - should not follow this
    - Drawbaceks:
        - sparsity
        - no fixed size
        - OOV
        - not capturing sementic meaning
```

2. bag of words
```
    - not capture sementic meaning
```

In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.DataFrame({
       "text":[
              "people watch dswithbappy",
              "dswithbappy watch dswithbappy",
              "people write comment",
              "dswithbappy write comment"],
       "output":[1,1,0,0]
})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

## Bag of words

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

# Unigrams
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])

In [27]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [28]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)

In [29]:
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]], dtype=int64)

In [30]:
X = bow.toarray()
y = df['output']

X

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)

## N-grams

In [31]:
# BI grams
# range(min, max)
cv = CountVectorizer(ngram_range=(2,2))
bow = cv.fit_transform(df['text'])

In [32]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [33]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]], dtype=int64)

In [34]:
#Ti gram
cv = CountVectorizer(ngram_range=(3,3))
bow = cv.fit_transform(df['text'])

In [35]:
cv.vocabulary_

{'people watch dswithbappy': 2,
 'dswithbappy watch dswithbappy': 0,
 'people write comment': 3,
 'dswithbappy write comment': 1}

In [36]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]], dtype=int64)

## TF-IDF (Term frequency-Inverse document frequency)
TF-IDF is used to measure the importance of words in a document relative to a collection of documents. 

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [39]:
arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [40]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
